name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Depedencies
        run: npm install

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_SECRET_KEY: ${{ secrets.MONGODB_CONNECTION_STRING }}

      - name: Run the tests
        run: npm test
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'cise-speed'
          heroku_email: 'charles@charlesmonaghan.com'
